name: Actions Runner Controller Demo

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  Explore-GitHub-Actions:
    # You need to use the INSTALLATION_NAME from the previous step
    runs-on: ashok-aiu-x86-64-arc-runner-set
    steps:
      - run: echo "🎉 This job uses runner scale set runners!"
