name: tests

on:
  push:
    branches: [main, cicd-experiments]
  pull_request:
    branches: [main, cicd-experiments]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  tests:
    name: pytest
    runs-on: self-hosted
    strategy:
      matrix:
        python-version: ['3.11', '3.12']
      fail-fast: false
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@eac588ad8def6316056a12d4907a9d4d84ff7a3b # v7.1.3
        with:
          enable-cache: true
          cache-dependency-glob: requirements/*

      - name: Create virtual environment
        run: uv venv

      - name: Install dependencies
        run: uv pip install -e ".[test,build]"

      - name: Run pytest
        run: pytest -v tests/
